### ISSUE TITLE
Migrate config info to a separate class?

### ISSUE THREAD

**Issue by andygup** [Esri/pubnub-delivery-tracking-demo#1]
Since we can't include `publishKey` and `subscribeKey` in the repo, it may make sense to pull out all the config info into a separate file/class/module. We are also currently doing a bit of duplication with the config info between `index.html` and `simulate-driver.html`.

If we go with this approach it will make submitting changes easier. We can simply bolt in our own credentials, feature services, sim services, etc and simply ignore changes to that file when we create a PR.

**Comment by jgravois** [comment]
agreed. ship `config.js.template` ask folks to make copy called `config.js` and put _that_ file in `.gitignore`
